#!/bin/bash

# Output used if there is no command line options selected.
usage() {
	printf "\n-----------------------------\n"
	printf " Usage: asus-lite [OPTION]..\n"
	printf "  -v		Display version\n"
	printf "  -t		Turbo mode\n"
	printf "  -b		Balanced mode\n"
	printf "  -s		Silent mode\n"
	printf "  -e		Enable dGPU\n"
	printf "  -d		Disable dGPU\n"
	printf "\n-----------------------------\n\n"
}

version() {
	printf "\nasus-lite 0.0.2\n\n"
}

turbo() {
	# Set the fans to 'turbo mode'
	echo 1 | sudo tee /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
}

balanced() {
	# Set fans to balanced or 'performance' mode
	echo 0 | sudo tee /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
}

silent() {
	# Sets the fans to silent, sometimes turning them off when nothing intense is happening on newer models
	echo 2 | sudo tee /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
}

dgpuon() {
	# Tells the laptop firmware to enable the dgpu (Only Nvidia is supported here.)
	modprobe nvidia
	echo 0 | sudo tee /sys/devices/platform/asus-nb-wmi/dgpu_disable
}

dgpuoff() {
	# Tells the laptop firmware to disable the dgpu (Only Nvidia is supported here)
	sudo modprobe -r nvidia
	echo 1 | sudo tee /sys/devices/platform/asus-nb-wmi/dgpu_disable
}

case "$1" in
	-v) version;;
	-s) silent;;
	-b) balanced;;
	-t) turbo;;
	-e) dgpuon;;
	-d) dgpuoff;;
	 *) usage; exit 1;;
esac
